# Training Hyperparameters
batch_size: 32
train_epochs: 30
lr: 0.1
log_dir: "./log.txt"
net_name: "ResNet18" #ResNet18, MobileNetV2
perform_qat: False
conv_mode: "quantize"
quant_sign: "symmetric"
fuse_bn: True
# HW Parameters
act_bit: 8
weight_bit: 6
partial_sum_size: 256
clamping_range_start: 2
clamping_range_mode: "per_layer" #per_layer, per_model
cim_signed_type: "unipolar" #unipolar, differential_pair
cim_input_type: "bit-parallel" #bit-parallel, 4-4, 3-3-2, bit-serial #NOT IMPLEMENTED