# Training Hyperparameters
batch_size: 32
train_epochs: 30
lr: 0.1
log_dir: "./log.txt"
net_name: "ResNet18" #ResNet18, MobileNetV2
qat: False
mode: "quantize"
quant_signedness: "symmetric"
# HW Parameters
act_bit: 8
weight_bit: 8
partial_sum_size: 256
range_start: 15
range_mode: "per_layer" #per_layer, per_model
signed_weight_approach: "differential_pair" #unipolar, differential_pair
cim_type: "bit-parallel" #bit-parallel, 4-4, 3-3-2, bit-serial #NOT IMPLEMENTED
fp_coprocessor: True #False case NOT IMPLEMENTED